[build]
builder = "nixpacks"

[build.env]
PYTHON_VERSION = "3.11"

[start]
cmd = "python main.py"

[variables]
PORT = "5000"
FLASK_APP = "main.py"
FLASK_ENV = "production"


[packages]
apt = ["libgl1-mesa-glx", "libsm6", "libxext6"]
[build]
# Specify the build directory. '.' means the root of the project.
build_dir = "."